# Custom Language File for Launcher Customizer

[ejs.app]
title = "Hasta Studios Launcher"

[ejs.landing]
mediaGitHubURL = "https://hastastudios.com.br"
mediaTwitterURL = "https://x.com/Zelthoriaismp87"
mediaInstagramURL = "https://www.tiktok.com/@_zsmp_"
mediaYouTubeURL = "https://youtube.com/@zsmpofc?si=bEThHknf_WXB7wqp"
mediaDiscordURL = "https://discord.gg/hastastudios"

[ejs.settings]
sourceGithubLink = "https://github.com/Shisuiicaro/HastaStudiosLauncher"
supportLink = "https://github.com/Shisuiicaro/HastaStudiosLauncher/issues"
selectLanguage = "Select a Language"
changeLanguageTitle = "Change the launcher language"
changeLanguageDesc = "You can change the language in the list below. This text will not change if you change the language so you can find your wayback here to change it back"

[ejs.welcome]
welcomeHeader = "WELCOME TO HASTA STUDIOS"
welcomeDescription = """
At Hasta Studios, innovation is at the heart of everything we do. From crafting immersive mods to managing extraordinary Minecraft servers, our mission is clear: to deliver the ultimate gaming experience for players around the globe.

This launcher is your gateway to a universe of adventure. With seamless access to all Hasta Studios servers, you can dive into breathtaking worlds, forge new stories, and explore challenges designed to inspire creativity and excitement.
"""

[ejs.overlay]
changedLanguageHeader = "You changed the previous language"